# Generated by Django 4.0.1 on 2022-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_abnormalinfo_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('stu_number', models.CharField(max_length=32, verbose_name='学号')),
                ('phone_number', models.CharField(max_length=32, verbose_name='手机号')),
                ('create_time', models.DateField(verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='PlacePlayground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('stu_number', models.CharField(max_length=32, verbose_name='学号')),
                ('phone_number', models.CharField(max_length=32, verbose_name='手机号')),
                ('create_time', models.DateField(verbose_name='时间')),
            ],
        ),
    ]
